language: node_js
node_js:
  - 0.10
install:
  - npm install -g gulp
  - npm install -g firebase-tools
  - bower install
  - npm install
  - gulp build
after_success:
  - firebase deploy --email ${FIREBASE_EMAIL} --password ${FIREBASE_PASSWORD}