language: node_js
node_js:
  - 0.10
install:
  - npm install gulp
  - npm install firebase-tools
  - gulp build
after_success:
  - firebase deploy --email ${FIREBASE_EMAIL} --password ${FIREBASE_PASSWORD}