language: node_js
node_js:
  - 0.10
install:
  - npm install -g firebase-tools
  - npm install -g mocha-phantomjs
  - npm install -g bower
  - bower install
  - npm install
  - npm install -g gulp
  - gulp build 
after_success:
  - firebase deploy --token '$FIREBASE_TOKEN'